### ISSUE TITLE
should we hash passwords in the frontend or the backend? 

### ISSUE THREAD

**Issue by samueljaval** [samueljaval/wes-favors-frontend#2]
i we hash in the front end, then we don't have the password going from the browser to the server as plain text. Well i guess if we are using httpS it probs would not be plain text but idk.

**Comment by samueljaval** [comment]
i think it should be backend, but we really have to make sure that we end up using https

**Comment by alpiazza13** [comment]
> i think it should be backend, but we really have to make sure that we end up using https

i'm inclined to agree
